{{- if and .Values.ingress.enabled .Values.ingress.extra }}
{{- range $name, $extra := .Values.ingress.extra }}
{{- $gateway := deepCopy $.Values.ingress.gateway | mustMerge ($extra.gateway | default dict) }}
{{- if $gateway.name }}
{{- $protocol := $.Values.ingress.protocol }}
{{- if $extra.port }}{{ $protocol = $extra.protocol }}{{ end }}

apiVersion: gateway.networking.k8s.io/v1beta1
kind: {{ if eq $protocol "http" }}HTTP{{ else if or (eq $protocol "grpc") (eq $protocol "h2c") }}GRPC{{ else }}{{ end }}Route
metadata:
  name: {{ include "generic-service.fullname" $ }}-{{ $name }}
  labels: {{- include "generic-service.default-labels" $ | nindent 4 }}
  annotations:
  {{- $merged := deepCopy ($.Values.ingress.annotations | default dict) | mustMerge ($extra.annotations | default dict) }}
  {{- range $mname, $mvalue := $merged }}
    {{- if ne $mvalue "nil" }}
      {{- dict $mname $mvalue | toYaml | nindent 4 }}
    {{- end }}
  {{- end }}

spec:
  parentRefs:
    - {{ $gateway | toYaml | nindent 6 }}

  hostnames: {{ $extra.domains | toYaml | nindent 4 }}

  {{- if eq $protocol "http" }}
  rules:
    {{- range ($extra.paths | default (list "/")) }}
    - matches:
        - path:
            value: {{ . | quote }}
      {{- if or $extra.timeoutSeconds $.Values.ingress.timeoutSeconds }}
      timeouts:
        backendRequest: {{ $extra.timeoutSeconds | default $.Values.ingress.timeoutSeconds }}s
      {{- end }}
      backendRefs:
        - name: {{ include "generic-service.fullname" $ }}
          port: {{ $extra.port | default $.Values.ingress.port }}
    {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
