{{- if .Values.monitoring.enabled }}

apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "generic-service.fullname" . }}
  labels: {{- include "generic-service.top-level-labels" . | nindent 4 }}
  {{- if and .Values.global.grafana.url .Values.global.grafana.dashboard }}
  annotations:
    link.argocd.argoproj.io/external-link: '{{ .Values.global.grafana.url }}/d/{{ .Values.global.grafana.dashboard }}?var-namespace={{ .Release.Namespace }}&var-service={{ include "generic-service.fullname" . }}'
  {{- end }}

spec:
  selector:
    matchLabels: {{- include "generic-service.selector-labels" . | nindent 6 }}

  podMetricsEndpoints:
    - port: {{ if and .Values.ingress.enabled (eq .Values.monitoring.port .Values.ingress.port) }}http-ingress{{ else }}http-monitoring{{ end }}
      path: {{ .Values.monitoring.path | quote }}
      interval: {{ .Values.monitoring.interval | quote }}

  podTargetLabels:
    - app
    - release
    {{- if eq .Values.rollout.controller "ArgoRollout" }}
    - role
    {{- end }}

{{- end }}
