# Argo Rollout controller BlueGreen test

image:
  repository: jwilder/whoami
  tag: latest

ingress:
  enabled: true
  port: 8000

rollout:
  controller: ArgoRollout
  strategy: BlueGreen
  blueGreen:
    autoPromotion: true
    prePromotionAnalysis:
      templates:
        - templateName: pod-ready
          clusterScope: true
        - templateName: success-rate
    postPromotionAnalysis:
      templates:
        - templateName: success-rate
        - templateName: pod-ready
          clusterScope: true
      args:
        - name: service-name
          value: canary-demo
  analysisTemplates:
    success-rate:
      args:
        - name: service-name
      metrics:
        - name: success-rate
          interval: 5m
          count: 10
          successCondition: "result[0] >= 0.95"
          query: |
            sum(irate(
              istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}",response_code!~"5.*"}[5m]
            )) /
            sum(irate(
              istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}"}[5m]
            ))
