# Ingress test

image:
  repository: jwilder/whoami
  tag: latest

ingress:
  enabled: true
  port: 8000
  timeoutSeconds: 5
  protocol: grpc
  domains: ['example.com']
  class: nginx

monitoring:
  enabled: true

alerting:
  enabled: true
