# InitContainer test

name: test
fullname: my-test

image:
  repository: jwilder/whoami
  tag: latest

initContainers:
  - name: init1
    image: docker/whalesay
    command: ["cowsay"]
    args: ["hi"]

initContainerTemplates:
  - |
      name: init2
      image: docker/whalesay:{{ .Values.image.tag }}
      command: ["cowsay"]
      args: ["hi"]
