# log alerts test

image:
  repository: jwilder/whoami
  tag: latest

alerting:
  enabled: true
  logs:
    levels:
      warning:
        severity: Warning
        maxCount: 10
      error: {}
    # setting this to an empty object (`{}`) will not suppress cm creation, use `null` instead
    lokiConfigMap: null
