# log alerts test

image:
  repository: jwilder/whoami
  tag: latest

alerting:
  enabled: true
  logs:
    levels:
      warning:
        severity: Warning
        maxCount: 10
      error: {}
    lokiConfigMap:
      label: "loki_rule"
      labelValue: ""
    createLokiRule: false
