# log alerts test

image:
  repository: jwilder/whoami
  tag: latest

alerting:
  enabled: true
  logs:
    levels:
      warning:
        severity: Warning
        maxCount: 10
      error: {}
    lokiSideCar:
      configMapLabel: "loki_rules"
      configMapLabelValue: ""
    createLokiRule: true
